version: "3.7"
services:

  #Laravel App
  app:
    build:
      args:
        user: muhammet
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mynetwork
  #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/
    networks:
      - mynetwork
  #MySQL Service
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - mynetwork
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.conf/my.cnf

networks:
  mynetwork:
    driver: bridge
volumes:
  db: